### ISSUE TITLE
Target Unity Asset Browser doesn't have .unity3D extension

### ISSUE THREAD

**Issue by AndySum** [Scrivener07/DisunityGuiHelper#1]
Hi! Great application so far, it makes disunity usable for me.

One problem I have is that the Target Unity Asset Browser doesn't have a .unity3D file extension, and so to open .unity3D files I have to manually type the filename which then works.

Can you add .unity3D to the available extensions (and/or a _._ type as well?).

**Comment by Scrivener07** [comment]
See if that does anything for you. https://github.com/Scrivener07/Barracuda/releases I removed the file filter so now all files are visible.

**Comment by AndySum** [comment]
Yep that works! Thanks :)
