### ISSUE TITLE
"Cant find java installation"

### ISSUE THREAD

**Issue by TurretProblems** [Scrivener07/DisunityGuiHelper#2]
Alright, followed the instructions, got "cant find java installation" when ive run it as admin, and its asking for the installation path.

**Comment by TurretProblems** [comment]
oh, and im not sure if this program is attempting to be malicous

**Comment by TurretProblems** [comment]
well, i feel like a slight moron, i just gave it the instalation path and now the GUI has shown up, thank goodness, the command promt Disunity is very difficult to use.

**Comment by Scrivener07** [comment]
Cool, Im glad this is still useful for people.
